version: "3.9"

services:
  app:
    build: .
    container_name: echo-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: echoapp
      DB_PORT: 5432
      REDIS_ADDR: redis:6379
      JWT_SECRET: dGhpcy1pcy1hLXNlY3VyZS1zZWNyZXQta2V5LWFzZGZhc2RmYXNkZg
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: echo-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: echoapp
      TZ: Asia/Jakarta   # ⬅️ tambahkan ini

    ports:
      - "5439:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: echo-redis
    ports:
      - "6379:6379"

volumes:
  db_data:
